
# A workflow, which builds the ComfyUI Docker image and publishes it to the GitHub Container Registry
name: Build and Publish Docker Images

# Configures this workflow to run when a tag was pushed to the repository that matches the pattern "v[0-9]+.[0-9]+.[0-9]+", which is a semantic
# versioning pattern; this token will be created when a new release is created; the release event cannot be used, because the docker/metadata-action
# action does not support the release event
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# Defines two custom environment variables for the host name of the registry (ghcr.io for the GitHub Container Registry) and the name of the image,
# which is set to the name of the repository
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# This workflow has a single job, which builds the Docker image and publishes it to the GitHub Container Registry
jobs:

  # The `build-and-publish` builds the Docker image, and publishes it to the GitHub Container Registry
  build-and-publish:
    strategy:
      matrix:
        PYTORCH_VERSION:
          - 2.5.1-cuda11.8-cudnn9
          - 2.5.1-cuda12.1-cudnn9
          - 2.5.1-cuda12.4-cudnn9
    env:
      LATEST_PYTORCH_VERSION: 2.5.1-cuda12.4-cudnn9
    # This job will run on an Ubuntu GitHub runner, which is a good default choice and it comes with Docker pre-installed
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    # This job 1) checks out the repository, 2) logs in to the GitHub Container Registry, 3) extracts metadata for the Docker image, 4) builds and
    # pushes the Docker image, and 5) generates an artifact attestation for the image
    steps:

      # Checks out the repository so that the workflow can access the files in the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Logs in to the GitHub Container Registry registry using the account of the user that triggered the workflow run and the GitHub token that is
      # an automatically generated secret that is usually only used to access the repository (the permissions defined above allow the token to also
      # publish Docker images to the GitHub Container Registry) that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extracts the latest versions of ComfyUI and the ComfyUI Manager from git; the versions are written to the output
      # file, which are available in subsequent steps under steps.versions.outputs.COMFYUI_VERSION and steps.versions.outputs.COMFYUI_MANAGER_VERSION;
      # the versions are used to tag the Docker image, so that users know which versions of ComfyUI and the ComfyUI Manager are included in the image
      - name: Extract ComfyUI & ComfyUI Manager Versions
        id: versions
        run: |
          echo "COMFYUI_VERSION=$(git ls-remote --tags --refs https://github.com/comfyanonymous/ComfyUI.git | grep -o 'v.*' | sort -V | tail -1)" >> "$GITHUB_ENV"
          echo "COMFYUI_MANAGER_VERSION=$(git ls-remote --tags --refs https://github.com/ltdrdata/ComfyUI-Manager.git | grep -o -E '[0-9]+\..*' | sort -V | tail -1)" >> "$GITHUB_ENV"
      
      - name: Check if image exists on GHCR
        id: image_check
        run: |
          echo "image_exists=false" >> "$GITHUB_OUTPUT"
          # ENCODED_TOKEN=$(echo -n "${{ secrets.GITHUB_TOKEN }}" | base64)
          # TAGS=$(curl -s -H "Authorization: Bearer ${ENCODED_TOKEN}" \
          #   https://ghcr.io/v2/${{ env.IMAGE_NAME }}/tags/list)
          # echo "TAGS: $TAGS"

          # ## Check if TAGS is empty or null
          # if [[ -z "$TAGS" || "$TAGS" == "null" ]]; then
          #   echo "No tags found, treating as image not existing."
          #   echo "image_exists=false" >> "$GITHUB_OUTPUT"
          # else
          #   ## Check if the specific tag already exists
          #   if echo "$TAGS" | jq -e --arg TAG "${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ matrix.PYTORCH_VERSION }}-cui-${{ env.COMFYUI_VERSION }}-cuim-${{ env.COMFYUI_MANAGER_VERSION }}" '.tags | index($TAG)'; then
          #     echo "Image with tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ matrix.PYTORCH_VERSION }}-cui-${{ env.COMFYUI_VERSION }}-cuim-${{ env.COMFYUI_MANAGER_VERSION }} already exists."
          #     echo "image_exists=true" >> "$GITHUB_OUTPUT"
          #   else
          #     echo "Image with tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ matrix.PYTORCH_VERSION }}-cui-${{ env.COMFYUI_VERSION }}-cuim-${{ env.COMFYUI_MANAGER_VERSION }} not found."
          #     echo "image_exists=false" >> "$GITHUB_OUTPUT"
          #   fi
          # fi

      - name: Set up tags
        id: tags
        if: ${{ steps.image_check.outputs.image_exists == 'false' }}
        run: |
          if [ "${{ matrix.PYTORCH_VERSION }}" = "${{ env.LATEST_PYTORCH_VERSION }}" ]; then
            echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ matrix.PYTORCH_VERSION }}-cui-${{ env.COMFYUI_VERSION }}-cuim-${{ env.COMFYUI_MANAGER_VERSION }}" >> "$GITHUB_OUTPUT"
          else
            {
              echo 'tags<<EOF'
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest-cui-${{ env.COMFYUI_VERSION }}-cuim-${{ env.COMFYUI_MANAGER_VERSION }}
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ matrix.PYTORCH_VERSION }}-cui-${{ env.COMFYUI_VERSION }}-cuim-${{ env.COMFYUI_MANAGER_VERSION }}
              echo EOF
            } >> "$GITHUB_OUTPUT"
          fi
          
      
      # Builds the Docker image for ComfyUI; if the build succeeds, it is pushed to the GitHub Container Registry; the "context" parameter specifies
      # the build context, which is the directory that contains the Dockerfile; the tags and labels extracted in the previous step are used to tag
      # and label the image
      - name: Build and Push Docker Image
        id: build-and-push-docker-image
        uses: docker/build-push-action@v6
        if: ${{ steps.image_check.outputs.image_exists == 'false' }}
        with:
          context: .
          push: true
          build-args: |
            PYTORCH_IMG_VERSION=${{ matrix.PYTORCH_VERSION }}
            COMFYUI_VERSION=${{ env.COMFYUI_VERSION }}
            COMFYUI_MANAGER_VERSION=${{ env.COMFYUI_MANAGER_VERSION }}
          tags: ${{ steps.tags.outputs.tags }}
          labels: |
            org.opencontainers.image.title=ComfyUI Docker
            org.opencontainers.image.authors=TheRealPSV


      # Generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built; it increases supply chain
      # security for people who consume the image
      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v1
        if: ${{ steps.image_check.outputs.image_exists == 'false' }}
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.build-and-push-docker-image.outputs.digest }}
          push-to-registry: true
